import { Resend } from "resend";
import { NextResponse } from "next/server";

// Fetch the API key from environments
const resendApiKey = process.env.resend || process.env.RESEND_API_KEY;
const resend = new Resend(resendApiKey);

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Comma separated lists, e.g. TESTER_SIGNUP_CC="a@example.com, b@example.com"
const parseAddresses = (value) =>
  (value || "")
    .split(",")
    .map((address) => address.trim())
    .filter(Boolean);

const escapeHtml = (value) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

export async function POST(req) {
  try {
    const body = await req.json().catch(() => null);

    if (!body || typeof body !== "object") {
      return NextResponse.json(
        { error: "Invalid request." },
        { status: 400 },
      );
    }

    // Honeypot: real users never see this field, bots fill it in. Pretend it
    // worked so the bot doesn't learn anything, but don't send an email.
    if (body?.company) {
      return NextResponse.json({ success: true });
    }

    const name = typeof body?.name === "string" ? body.name.trim() : "";
    const email = typeof body?.email === "string" ? body.email.trim() : "";
    const phone = typeof body?.phone === "string" ? body.phone.trim() : "";

    // Validate the required fields
    if (!name || !email) {
      return NextResponse.json(
        { error: "Name and email address are required." },
        { status: 400 },
      );
    }

    if (!EMAIL_PATTERN.test(email) || email.length > 254) {
      return NextResponse.json(
        { error: "Please enter a valid email address." },
        { status: 400 },
      );
    }

    if (name.length > 100 || phone.length > 40) {
      return NextResponse.json(
        { error: "Some of the details you entered are too long." },
        { status: 400 },
      );
    }

    // Email configurations
    const recipients = parseAddresses(process.env.TESTER_SIGNUP_TO);
    const cc = parseAddresses(process.env.TESTER_SIGNUP_CC);
    const sender = "app@zimbabwhere.com";

    const safeName = escapeHtml(name);
    const safeEmail = escapeHtml(email);
    const safePhone = escapeHtml(phone);

    // Call Resend to send the email
    const { data, error } = await resend.emails.send({
      from: `Zimbabwhere App Testers <${sender}>`,
      to: recipients.length ? recipients : ["zimbabadvertising@gmail.com"],
      ...(cc.length ? { cc } : {}),
      replyTo: email,
      subject: `New App Tester Sign-up: ${email}`,
      html: `
        <div style="font-family: 'Roboto', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #3a3a3a; background-color: #2e2e2e; color: #ffffff; border-radius: 6px;">
          <h2 style="color: #2cb75f; font-family: 'BankGothic', sans-serif; border-bottom: 2px solid #32cd32; padding-bottom: 10px; margin-top: 0;">
            New App Tester Sign-up
          </h2>
          <p style="margin: 16px 0 8px 0; font-weight: bold; color: #2cb75f;">
            Google Play email (add this to the tester list):
          </p>
          <div style="background-color: #1f1f1f; padding: 12px; border-radius: 4px; border-left: 3px solid #32cd32; font-size: 16px; font-weight: bold;">
            ${safeEmail}
          </div>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f; width: 180px;">Name:</td>
              <td style="padding: 8px 0; color: #ffffff;">${safeName}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f;">Phone / WhatsApp:</td>
              <td style="padding: 8px 0; color: #ffffff;">${safePhone || "Not provided"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f;">Confirmed Android user:</td>
              <td style="padding: 8px 0; color: #ffffff;">Yes</td>
            </tr>
          </table>
          <div style="margin-top: 30px; border-top: 1px solid #3a3a3a; padding-top: 15px; font-size: 12px; color: #888;">
            This email was automatically generated by Zimbabwhere Web App's app tester sign-up page. Reply to this email to contact the tester.
          </div>
        </div>
      `,
    });

    if (error) {
      console.error("❌ Resend Email Error:", error);
      return NextResponse.json(
        { error: "We couldn't send your sign-up. Please try again." },
        { status: 500 },
      );
    }

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error("❌ Server Error in API Route:", error);
    return NextResponse.json(
      { error: "Something went wrong. Please try again." },
      { status: 500 },
    );
  }
}
