import { Resend } from "resend";
import { NextResponse } from "next/server";

// Fetch the API key from environments
const resendApiKey = process.env.resend || process.env.RESEND_API_KEY;
const resend = new Resend(resendApiKey);

export async function POST(req) {
  try {
    const body = await req.json();
    const { name, surname, email, phone, headingName } = body;

    // Validate the required fields
    if (!name || !surname || !email || !headingName) {
      return NextResponse.json(
        { error: "Name, surname, email, and heading name are required." },
        { status: 400 },
      );
    }

    // Email configurations
    const recipient = "zimbabadvertising@gmail.com";
    const sender = "app@zimbabwhere.com";

    // Call Resend to send the email
    const { data, error } = await resend.emails.send({
      from: `Zimbabwhere Headings <${sender}>`,
      to: recipient,
      replyTo: email,
      subject: `New Heading Request: ${headingName}`,
      html: `
        <div style="font-family: 'Roboto', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #3a3a3a; background-color: #2e2e2e; color: #ffffff; border-radius: 6px;">
          <h2 style="color: #2cb75f; font-family: 'BankGothic', sans-serif; border-bottom: 2px solid #32cd32; padding-bottom: 10px; margin-top: 0;">
            New Heading Request
          </h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f; width: 180px;">Requestor Name:</td>
              <td style="padding: 8px 0; color: #ffffff;">${name} ${surname}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f;">Email Address:</td>
              <td style="padding: 8px 0; color: #ffffff;"><a href="mailto:${email}" style="color: #32cd32; text-decoration: none;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f;">Phone Number:</td>
              <td style="padding: 8px 0; color: #ffffff;">${phone || "Not provided"}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #2cb75f;">Requested Heading:</td>
              <td style="padding: 8px 0; color: #ffffff; font-size: 16px; font-weight: bold; background-color: #1f1f1f; padding: 8px 12px; border-radius: 4px; border-left: 3px solid #32cd32;">
                ${headingName}
              </td>
            </tr>
          </table>
          <div style="margin-top: 30px; border-top: 1px solid #3a3a3a; padding-top: 15px; font-size: 12px; color: #888;">
            This email was automatically generated by Zimbabwhere Web App's heading request feature.
          </div>
        </div>
      `,
    });

    if (error) {
      console.error("❌ Resend Email Error:", error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error("❌ Server Error in API Route:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
